### ISSUE TITLE
[AI Decision Engine] Kubernetes Scheduler configuration that uses AI scoring plugin

### ISSUE THREAD

**Issue by ktatarnikovhiro** [glaciation-heu/IceStream#194]

**Comment by armantorkzaban** [comment]
WILL BE UPDATED

To use the AI scoring plugin we need to take 3 steps:

**Step 1: Create a Custom Scheduler**
Configuration File:
We first, create a configuration file for our custom AI scoring plugin. This file will define the behavior of the scheduler.
Here’s an example:

```
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: AI-scheduler
  leaderElection:
    leaderElect: false
…
```

**Deploy the Scheduler:**
Deploy our custom scheduler as a Pod in the Kubernetes cluster, typically in the kube-system namespace.
We will also need to create a ConfigMap to store our configuration and a Deployment for the scheduler

**Step 2: Label Our Deployment**
When creating our deployment, we can specify which scheduler to use by adding the `schedulerName` field in the pod specification. Here’s how we can do it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
        scheduler-type: AI-scheduler  # Label indicating the custom scheduler
    spec:
      schedulerName: AI-scheduler    # Specify the custom scheduler here
      containers:
      - name: my-app-container
        image: my-app-image
```

In this example, scheduler-type: `AI-scheduler` is a label that indicates which scheduler should be used. The schedulerName field in the pod spec must match the name defined in our custom scheduler configuration

**Step 3: Deploy Our Application**

`kubectl apply -f my-deployment.yaml
`
